name: camopurge
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Camo Purge Action
        uses: kevincobain2000/action-camo-purge@v1
